# Generated by Django 5.2.16 on 2026-07-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_round_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='payout_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
